### ISSUE TITLE
Redforce ToDo

### ISSUE THREAD

**Issue by Redforce04** [LethalCompany/LCAPI.Core#29]

**Comment by Redforce04** [comment]
- [x] Switch to proper template.
- [ ] Push new wiki documentation.
- [ ] Finish Save System
- [x] Push Json Converters
- [x] Implement Nuget packages for all plugins.
- [ ] Implement Automated Testing for PR requests.
- [ ] Implement Automated Build System.

**Comment by Redforce04** [comment]
it may not be my first issue but I'd call it a good one

**Comment by ManindraDeMel** [comment]
I see that push new wiki documentation is a task on the list. Was wondering if there was any documentation for this API at all anywhere?
